name: Releasing
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: Release Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test application
        run: go test ./...
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Capture git tag
        id: vars
        run: |
          echo "tag=$(git describe --tags --abbrev=0 || echo "0.0.0-devel")" >> $GITHUB_OUTPUT
      - name: Replace version in plugin.yaml
        run: |
          yq e ".version = \"${{ steps.vars.outputs.tag }}\"" -i plugin.yaml
      - name: Release application to Github
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
